### ISSUE TITLE
Feature request: add support for Sista bytecode set

### ISSUE THREAD

**Issue by ErikOnBike** [codefrau/SqueakJS#108]
Hi Vanessa,

Just putting it here for others to see as well. Maybe someone is interested to participate as well.

Cheers,
Erik

**Comment by codefrau** [comment]
For anyone interested: the SISTA bytecode set is well-explained in Clément and Eliot's paper:
https://www.researchgate.net/publication/280793584_A_bytecode_set_for_adaptive_optimizations

All that's needed at first is writing another `interpretOne` method which fetches and interprets one bytecode at a time.

To get performance up to the speed of the traditional bytecode set, another JIT would be needed. This is also relatively simple since the current JIT only accelerates instruction decoding. I'd probably just copy the current JIT to a new file and use it as a template for the new one.

**Comment by codefrau** [comment]
Very helpful comments from @clementbera 
http://forum.world.st/Sista-byte-code-documentation-tp5119159p5119160.html

**Comment by codefrau** [comment]
Thanks to @fniephaus we do have Sista support now (albeit without JIT)
