### ISSUE TITLE
Could find method (sic) for current ABI: UNKNOWN_ABI 

### ISSUE THREAD

**Issue by SimonXHolland** [codefrau/SqueakJS#175]
Running my image in  https://squeak.js.org/run/ in Safari 17.5

On startup I get: Error: Could find method for current ABI: UNKNOWN_ABI 
(In fact if I just  dismiss the error things seem to work, but I don’t know if it might be causing later problems.)

Debugger gives:
Error: Could find method for current ABI: UNKNOWN_ABI FFIPlatformDescription(Object)>>error: 
FFIPlatformDescription>>abiSend:to: 
FFICallbackContext class>>fields FFICallbackContext class(ExternalStructure class)>>referencedTypeNames ExternalStructure class>>allStructuresInCompilationOrder ExternalStructure class>>defineAllChangedFields ExternalType class>>initializeFast ExternalType class>>platformChangedFrom:to: 
[ ] in [ ] in [  ] in FFIPlatformDescription class>>startUp: Array(SequenceableCollection)>>do:
[ ] in [ ]  in FFIPlatformDescription class>>startUp: 
[ ] in FFIPlatformDescription (Object)  >> in: 
[ ] in FFIPlatformDescription class>>startUp: 
[ ] in SmalltalkImage>>send:toClassesNamedIn:with: 
OrderedCollection>>do: 
SmalltalkImage>>send:toClassesNamedIn:with: SmalltalkImage>>processStartUpList: 
SmalltalkImage>>startUpPostSnapshot:

In the method at the top of the stack:  FFIPlatformDescription>>abiSend: to: 
The first argument is #fields, the second argument is FFICallbackContext

The method dictionary for FFICallbackContext
 Looks like this:
#mostRecent "a CompiledMethod(3713187)"
#externalType "a CompiledMethod(500449)"
#'fields_ARM64' "a CompiledMethod(1476276)"
#'fields_IA32' "a CompiledMethod(2478328)" 
#primMostRecentCallbackContextAddress "a CompiledMethod(3829429)" 
#fields "a CompiledMethod(3828383)" 
#'fields_X64' "a CompiledMethod(3019174)" 
#'fields_X64Win64' "a CompiledMethod(583382)”
#fromHandle: "a CompiledMethod(2822279)" 
#'fields_ARM32' "a CompiledMethod(674973)"

**Comment by codefrau** [comment]
If your image actually depends on FFI then it’s unlikely to work in SqueakJS. If it doesn’t, the easiest would be to unload the FFI package. What image is this? 

SqueakJS does support the "old" FFI (e.g. in https://github.com/codefrau/jasmine which uses OpenGL via FFI). Not sure what this one is, but we could implemented that kind of FFI for sure. 

However, if it actually tries to execute foreign functions, it would require to emulate those functions since you can't actually load C functions in JavaScript. That's what I did in Jasmine, and there's a generic `libc` file here in this repo [ffi/libc.js ](https://github.com/codefrau/SqueakJS/blob/main/ffi/libc.js).

A really cool project would be to try compiling a C library to WASM and then making the FFI be able to execute functions from the WASM module. But that's a whole research project.

**Comment by SimonXHolland** [comment]
Hi Vanessa, thanks for very helpful and speedy reply. The FFI that I was using is for Stephen Pope's  portMIDI plugin which is used to make midi work on MacOS (although I wasn’t attempting to route anything via that plugin here)
Now I know what is happening I can easily work around it - thanks!

**Comment by codefrau** [comment]
Ah. So it might work if you just disable the `checkFFIOnStartUp` preference.
