### ISSUE TITLE
Hourglass icon is infinitely rotate in a center.

### ISSUE THREAD

**Issue by bemoregt** [codefrau/SqueakJS#179]
Hi, @tonyg @zot @jsparkes @timfel @krono 

I have met this error when run your SqueakJS with my swikiswiki image.

My swiki image is well loaded to run webpage,

But, then a Hourglass icon is infinitely rotate in a center.

What's wrong to me ??

Thanks in advance.
Best,

@bemoregt.

**Comment by LinqLover** [comment]
Do you see any error messages in the browser console (e.g., <kbd>F12</kbd> in Chrome)?

**Comment by codefrau** [comment]
Your "swiki image" likely is trying to start the swiki web server. That is not supported by SqueakJS because it runs in a web page itself so cannot be a server for other pages. 

You can try to press cmd-. (command and period, or maybe alt-period) to interrupt the startup process, which may allow you to use the image interactively. But you won't be able to start the Swiki server.

**Comment by codefrau** [comment]
Closing for lack of response

**Comment by zot** [comment]
Thinking about this, some day someone might want to look at trying to proxy Squeak HTTP services with service workers using the technique illustrated here:

https://itnext.io/how-to-create-web-server-in-browser-ffaa371d2b53

**Comment by codefrau** [comment]
Interesting idea. This would still only work in the same browser ... so you could browse the Swiki locally, but not from elsewhere. 

Another idea would be to emulate a full TCP/IP stack and funnel packets through some other form of transport. [I actually did that](https://github.com/codefrau/jasmine/blob/main/jasmine-socket-plugin.js) and it's working to some extent, but not entirely complete or tested.
