### ISSUE TITLE
PNG decoder bug: some forms are yellow

### ISSUE THREAD

**Issue by marceltaeumel** [codefrau/SqueakJS#23]
![squeakjs-vivide-forms](https://cloud.githubusercontent.com/assets/5765308/5414928/53a3d7fa-8223-11e4-880c-d77da64f4fcc.png)

It could be an alpha-blending bug...

**Comment by codefrau** [comment]
More clues:

up to 4.4: fine (https://squeak.js.org/run/#zip=https://files.squeak.org/4.4/Squeak4.4-12327.zip)

since 4.5: broken (https://squeak.js.org/run/#zip=https://files.squeak.org/4.5/Squeak4.5-13680.zip)

Filing in 4.4's PNGReadWriter>>copyPixelsRGB: fixes the issue.

[PNGReadWriter-copyPixelsRGB.st.zip](https://github.com/codefrau/SqueakJS/files/10832536/PNGReadWriter-copyPixelsRGB.st.zip)

Still not sure if it's an image bug or VM bug.

**Comment by codefrau** [comment]
Thanks to Agustin Martinez for isolating the bad `BitBlt` call! 

It failed when a color map had negative shifts because it was accessed as a `UInt32Array`. The fix above makes it use an `Int32Array` instead.
